Models/CuisineType.cs
using System;
namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        Peruvian
    }
}

Models/Restaurant.cs
using System;
namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }
    }
}

Models/RestaurantEditModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Models
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name
        {
            get;
            set;
        }

        public CuisineType Cuisine
        {
            get;
            set;
        }

        public RestaurantEditModel()
        {
        }
    }
}

ViewModels/HomeIndexViewModel.cs
using System;
using System.Collections.Generic;
using OdeToFood.Models;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set;}

        public string CurrentMessage { get; set; }

        public HomeIndexViewModel()
        {
        }
    }
}

Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.Controllers
{
    [Route("[controller]/[action]")]
    public class AboutController
    {
        public string Phone()
        {
            return "+1 929 281 8855";
        }

        public string Address()
        {
            return "226 57th st.";
        }
    }
}

Controllers/HomeController.cs
using System;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace OdeToFood.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        IRestaurantData _restaurantService;
        IGreeterService _greeterService;

        public HomeController(IRestaurantData restaurantService, IGreeterService greeterService)
        {
            _restaurantService = restaurantService;
            _greeterService = greeterService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = new HomeIndexViewModel
            {
                Restaurants = _restaurantService.GetAll(),
                CurrentMessage = _greeterService.GetMessageOfTheDay()
            };
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var restaurant = _restaurantService.Get(id);

            if (restaurant == null)
                //return NotFound();
                return RedirectToAction(nameof(Index));

            return View(restaurant);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(RestaurantEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var restaurant = new Restaurant();
            restaurant.Name = model.Name;
            restaurant.Cuisine = model.Cuisine;

            restaurant = _restaurantService.Add(restaurant);

            return RedirectToAction(nameof(Details), new { id = restaurant.Id });

        }

    }
}

Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeterService _greeter;

        public string CurrentString { get; set; }

        public GreetingModel(IGreeterService greeter)
        {
            _greeter = greeter;
        }

        public void OnGet(string name)
        {
            CurrentString = $"{name} :: {_greeter.GetMessageOfTheDay()}!!!";
        }
    }
}

ViewComponents/GreeterViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        IGreeterService _greeter;

        public GreeterViewComponent(IGreeterService greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();

            return View("Default", model);
        }
    }
}

Pages/Greeting.cshtml
@page "{name}"
@model GreetingModel

@{
    ViewBag.Title = "Greeting!!!";
}

<div>@Model.CurrentString</div>

Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
    </footer>        
</body>
</html>

Views/Home/Create.cshtml
@model Restaurant

@{
    ViewBag.Title = "Create";
}

<form  method="post" >

    <div>
        <label asp-for="Name" ></label>
        <input asp-for="Name" />    
        <span asp-validation-for="Name"></span>
    </div>

    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"  asp-items="@Html.GetEnumSelectList<CuisineType>()" > </select>
        <span asp-validation-for="Cuisine"></span>
       
    </div>
 
    

    <input type="submit" name="save" value="Save" />
</form>

Views/Home/Details.cshtml
@model Restaurant

@{
    ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>

<div>Id : @Model.Id</div>
<div>Cuisine : @Model.Cuisine XX</div>

<a asp-action="Index" asp-controller="Home">Home</a>

Views/Home/Index.cshtml
@model HomeIndexViewModel

@{
    ViewBag.Title = "Home Page";
}

<h1>All Restaurants</h1>

@foreach(var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)
}

<div>
    <a asp-action="Create">Add Restaurant</a>
</div>

@section footer{
    @Model.CurrentMessage
}

Views/Home/_Summary.cshtml
@model Restaurant

<section>

    <h3>@Model.Name</h3>

    <div>   
        Cuisine : @Model.Cuisine
    </div>

    <div>
        <a href="/home/details/@Model.Id">details</a> 
        @Html.ActionLink("Go", "Details", new {id = Model.Id } )   
        <a asp-action="Details" asp-route-id="@Model.Id">More</a>
    </div>
</section>

Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>@Model</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

        <environment include="Development">
            <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position"
                  asp-fallback-test-value="absolute" />
        </environment>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
        @await Component.InvokeAsync("Greeter")
        <vc:greeter></vc:greeter>

            @if(User.Identity.IsAuthenticated)
            {
                foreach(var identity in User.Identities)
                {
                    <h3>@identity.Name</h3>
                    <ul>
                        @foreach(var claim in identity.Claims)
                        {
                            <li>@claim.Type - @claim.Value</li>
                        }
                    </ul>
                }
            }
            else
            {
                <div>You are anonymous</div>
            }
    </footer>   
        <environment include="Development">
            <script src="~/node_modules/jquery/dist/jquery.js"> </script>
            <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"> </script>
            <script src="~/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"> </script>
        </environment>

        <environment exclude="Development">
            <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.3.min.js"
                    asp-fallback-src="/node_modules/jquery/dist/jquery.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
                    asp-fallback-src="/node_modules/jquery-validation/dist/jquery.validate.js"
                    asp-fallback-test="window.jQuery && window.jQuery.validator">
            </script>
            <script src="http://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
                    asp-fallback-src="/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"
                    asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
            </script>
        </environment>
</body>
</html>